### ISSUE TITLE
Build first iteration of action-publish-cpan

### ISSUE THREAD

**Issue by mattwynne** [cucumber/action-publish-cpan#1]
### 🤔 What's the problem you're trying to solve?

We need this github action so that we can add a `release-cpan.yml` to https://github.com/cucumber/messages/pull/27

### ✨ What's your proposed solution?

Port the code over from https://github.com/cucumber/common/blob/main/.templates/perl/default.mk

Ideally, add a test package and a github workflow to this repo to test that it actually works. See [the npm action](https://github.com/cucumber/action-publish-npm/blob/main/.github/workflows/test.yaml) for an example.

### 📚 Any additional context?

https://github.com/cucumber/common/issues/2029

----

*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/feature_request.md)*

**Comment by mattwynne** [comment]
@ehuelsmann can you help?

**Comment by mattwynne** [comment]
Note that CPAN uses a `.pause` file to authenticate, so we'll probably need to write this file from a secret.

**Comment by mattwynne** [comment]
@ehuelsmann I've got somewhere, but it's currently failing to find the `dzil` binary in the `PATH` on the GitHub Action container. How do we find out where `cpanm` has installed it?

**Comment by mattwynne** [comment]
I figured out the path thing, by [installing perl ourselves](https://github.com/cucumber/action-publish-cpan/commits/4d6e8d27d81be28045fb3b5c3b5771dc95030ae8) but now it's giving [an error](https://github.com/cucumber/action-publish-cpan/runs/7862050935?check_suite_focus=true) when we run `dzil build`:

```
Attribute (_version_override) does not pass the type constraint because: $version is not a valid lax version string at constructor Dist::Zilla::Dist::Builder::new (defined at /usr/local/share/perl/5.30.0/Dist/Zilla/Dist/Builder.pm line 888) line 102
```

**Comment by mattwynne** [comment]
OK I figured that out too. If you want to use a semver-style version number you need to [prefix it with a `v`](http://blogs.perl.org/users/grinnz/2018/04/a-guide-to-versions-in-perl.html)

**Comment by mattwynne** [comment]
Nope, [that didn't work](https://github.com/cucumber/action-publish-cpan/actions/runs/2870620785). I can only seem to make the `dzil` we get on the GitHub Actions container accept a "numeric" version like `0.003`. It works fine on my local machine.

**Comment by mattwynne** [comment]
In order to try and work out why it was different on my machine, I added some version number printing.

The GHA container has perl v5.30.0, wheras I have v5.34.0 locally.

They both end up with `dzil` 6.025 though.

**Comment by ehuelsmann** [comment]
`dzil` is compatible with any Perl 5.20.0 or up; so the version difference shouldn't be a problem.

**Comment by mattwynne** [comment]
I've modified it to use the same mechanism we use in the monorepo, leaning on `[Hook::VersionProvider]` to read the version in from a `VERSION` file. That seems to be working. I think I'm almost there!

**Comment by mattwynne** [comment]
I wish I'd done this in a branch now, rather than cluttering up `main`

**Comment by mattwynne** [comment]
OK I reset the `main` branch back to the beginning and you can now follow along in #2
